# Generated by Django 2.2.12 on 2020-05-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_item_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='test',
            new_name='text',
        ),
    ]
