# Generated by Django 2.2.12 on 2020-05-30 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CV', '0002_institute_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='CV.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='SectionElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='CV.Section')),
            ],
        ),
        migrations.DeleteModel(
            name='Element',
        ),
    ]
